---
- name: 'Use system playbook check_system'
  ansible.builtin.import_role:
    name: system
    tasks_from: check_system

- name: 'Use system playbook default_ssh_key'
  ansible.builtin.import_role:
    name: system
    tasks_from: default_ssh_key

