---
- name: Playbook for Mageai Infra server installation
  hosts: all
  gather_facts: true

  tasks:
    - name: Include variables for the underlying distribution
      ansible.builtin.include_vars: "{{ ANSIBLEDIR }}/group_vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

    - name: Base setup for a Mageia Infra server
      ansible.builtin.include_tasks: "{{ ANSIBLEDIR }}/install_base_system.yml"

    - name: Ensure all required packages for {{ MGATYPE }} are installed
      become: true
      become_user: root
      ansible.builtin.package:
        name:
          #- acl
          #- moreutils
          #- net-tools
          #- netkit-telnet
          #- unzip
          #- patch
          #- expect
        state: present
        update_cache: true

    - name: Ensure required directories under /usr/local are owned by "{{ MGAUSER }}"
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ MGAUSER }}"
        group: "{{ MGAUSER }}"
        mode: "0755"
      with_items:
        - /usr/local/bin
        - /usr/local/sbin
        - /usr/local/share

    - name: Ensure that this a compliant Mageia system
      ansible.builtin.include_tasks: "{{ ANSIBLEDIR }}/check_fiona.yml"
